# Generated by Django 3.2.5 on 2022-08-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel_name', models.CharField(max_length=255)),
                ('hostel_address', models.TextField()),
                ('hostel_contact_no', models.IntegerField()),
                ('hostel_fees', models.IntegerField()),
                ('hostel_type', models.CharField(choices=[('G', 'Gents'), ('L', 'Ladies')], max_length=2)),
                ('location_url', models.URLField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='webpage',
            name='topic',
        ),
        migrations.DeleteModel(
            name='AccessRecord',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
        migrations.DeleteModel(
            name='Webpage',
        ),
    ]
