# Generated by Django 3.2.5 on 2022-08-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_auto_20220806_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostels',
            name='hostel_image',
            field=models.ImageField(null=True, upload_to='hostels_images'),
        ),
    ]
