# Generated by Django 3.2.5 on 2022-08-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_hostels_hostel_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostels',
            old_name='hostel_image',
            new_name='hostel_image1',
        ),
        migrations.AddField(
            model_name='hostels',
            name='hostel_image2',
            field=models.ImageField(null=True, upload_to='hostels_images'),
        ),
        migrations.AddField(
            model_name='hostels',
            name='hostel_image3',
            field=models.ImageField(null=True, upload_to='hostels_images'),
        ),
        migrations.AddField(
            model_name='hostels',
            name='hostel_image4',
            field=models.ImageField(null=True, upload_to='hostels_images'),
        ),
        migrations.AddField(
            model_name='hostels',
            name='hostel_image5',
            field=models.ImageField(null=True, upload_to='hostels_images'),
        ),
    ]
