# Generated by Django 3.2.5 on 2022-08-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_auto_20220807_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostels',
            old_name='hostel_fees',
            new_name='hostel_rent',
        ),
        migrations.AddField(
            model_name='hostels',
            name='mess_fees',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='hostels',
            name='hostel_image1',
            field=models.ImageField(default='hostels_images/1.jpg', null=True, upload_to='hostels_images'),
        ),
        migrations.AlterField(
            model_name='hostels',
            name='hostel_image2',
            field=models.ImageField(default='hostels_images/1.jpg', null=True, upload_to='hostels_images'),
        ),
        migrations.AlterField(
            model_name='hostels',
            name='hostel_image3',
            field=models.ImageField(default='hostels_images/1.jpg', null=True, upload_to='hostels_images'),
        ),
        migrations.AlterField(
            model_name='hostels',
            name='hostel_image4',
            field=models.ImageField(default='hostels_images/1.jpg', null=True, upload_to='hostels_images'),
        ),
        migrations.AlterField(
            model_name='hostels',
            name='hostel_image5',
            field=models.ImageField(default='hostels_images/1.jpg', null=True, upload_to='hostels_images'),
        ),
    ]
