# Generated by Django 3.2.5 on 2022-08-11 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_auto_20220811_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostels',
            name='hostel_contact_no',
            field=models.TextField(),
        ),
    ]
